skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
goalana_program = "4x5y2L5V6NfbZDLJa7KFcESb8dt8DptAcv53iKNteBgM"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
